//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id_customer { get; set; }
        public string nome { get; set; }
        public int sexo { get; set; }
        public int id_cidade { get; set; }
        public int id_regiao { get; set; }
        public System.DateTime ultima_compra { get; set; }
        public int id_classificacao { get; set; }
        public int id_usuario { get; set; }
        public int ativo { get; set; }
        public string phone { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual classificacao classificacao { get; set; }
        public virtual regiao regiao { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
