//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAOModelEntities : DbContext
    {
        public DAOModelEntities()
            : base("name=DAOModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cidade> cidades { get; set; }
        public virtual DbSet<classificacao> classificacoes { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<nivel_acesso> niveis_acesso { get; set; }
        public virtual DbSet<regiao> regioes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
