//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class regiao
    {
        public regiao()
        {
            this.customers = new HashSet<customer>();
        }
    
        public int id_regiao { get; set; }
        public int id_cidade { get; set; }
        public string nome { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual ICollection<customer> customers { get; set; }
    }
}
