//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.customers = new HashSet<customer>();
        }
    
        public int id_usuario { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public int cidade { get; set; }
        public int valor_nivel_acesso { get; set; }
        public int ativo { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
        public virtual nivel_acesso nivel_acesso { get; set; }
    }
}
